http://localhost:8080/api/movies

###

http://localhost:8080/api/movies/6709346b8fe18d726130a5a1

###

DELETE http://localhost:8080/api/movies/670db8d2ab8f37463e496fc7

###

POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": "開発ウェブ開発WordPress【2024最新】中級者向けWordPress自作テーマ講座（カスタム投稿、ウィジェット実装などが学べる）",
    "instructor": "はしもと よしみつ",
    "rating": 4,
    "comment": "静的ファイルからCMS化するための方法がわかりやすく説明されていました。ただこちらの動画も関数の説明がイマイチだったのでWordPressの習得はあまり進んでいないように感じました。"
}

###

PATCH http://localhost:8080/api/movies/670db8d2ab8f37463e496fc7
Content-Type: application/json

{
    "img": ""
}