http://localhost:8080/api/movies

###

http://localhost:8080/api/movies/6709346b8fe18d726130a5a1

###

DELETE http://localhost:8080/api/movies/670532cf86e797619708ed89

###

POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": "ちゃんと学ぶ、WordPress テーマ開発講座",
    "instructor": "たにぐち まこと",
    "img": "TaniguchiMakoto_wordpress.jpg",
    "rating": 3,
    "comment": "PHPを学習したのでCMS分野も勉強しようと思い学習を始めました。関数の紹介はあるのですが、どういうケースで使うか、なぜそうなるか、などの説明が省略されており学習コンテンツとしては微妙でした。"
}

###

PATCH http://localhost:8080/api/movies/67053c1dd1f4b81e148459ff
Content-Type: application/json

{
    "title": "テストタイトル"
}