http://localhost:8080/api/movies

###

http://localhost:8080/api/movies/6709346b8fe18d726130a5a1

###

DELETE http://localhost:8080/api/movies/670db8d2ab8f37463e496fc7

###

POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": "test",
    "instructor": "test",
    "rating": 3,
    "comment": "test"
}

###

PATCH http://localhost:8080/api/movies/670db8d2ab8f37463e496fc7
Content-Type: application/json

{
    "img": ""
}